spring:
  datasource:
    url: jdbc:h2:mem:purchase-cart-service;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 9090